# 🚀 Project Atlas

# Day 7 – NumPy Revision & Self-Assessment

**Date:** July 12, 2026  
**Theme:** NumPy Consolidation  
**Difficulty:** ⭐⭐⭐☆☆  
**Rules:** No notes, no previous notebooks, and no internet while solving.

---

## 🎯 Objective

The goal of this assessment is to test how comfortably I can apply NumPy concepts without referring to previous solutions.

This assessment covers:

- Array exploration
- Aggregation
- Axis operations
- Boolean masking
- Broadcasting
- Sorting and ranking
- Summary table creation
- Business interpretation

# 📊 Assessment Dataset

The dataset represents sales for **5 products across 5 weeks**.

- Rows represent weeks.
- Columns represent products.
- Values represent sales in ₹ thousands.

## Dataset

```text
[
 [25, 40, 38, 50, 45],
 [30, 42, 36, 55, 47],
 [28, 45, 40, 53, 49],
 [35, 48, 42, 60, 52],
 [33, 46, 41, 58, 50]
]

In [1]:
import numpy as np
sales = np.array([
 [25, 40, 38, 50, 45],
 [30, 42, 36, 55, 47],
 [28, 45, 40, 53, 49],
 [35, 48, 42, 60, 52],
 [33, 46, 41, 58, 50]
]
)
print(sales)

[[25 40 38 50 45]
 [30 42 36 55 47]
 [28 45 40 53 49]
 [35 48 42 60 52]
 [33 46 41 58 50]]


# 🧪 NumPy Self-Assessment

Complete all tasks without using explicit loops.

---

## Task 1 – Dataset Exploration

Find:

- Shape
- Size
- Number of dimensions
- Data type
- Number of weeks
- Number of products

In [3]:
#Shape
print("Shape : ",np.shape(sales))
#Size
print("Size : ",np.size(sales))
#Number of dimensions
print("Number of dimensions : ",np.ndim(sales))
#Data type
print("Datatype : ",sales.dtype)
#Number of weeks
weeks, products = np.shape(sales)
print("Number of weeks : ",weeks)
#Number of products
print("Number of products : ",products)

Shape :  (5, 5)
Size :  25
Number of dimensions :  2
Datatype :  int64
Number of weeks :  5
Number of products :  5


## Task 2 – Product-Wise Analysis

Calculate:

- Product-wise totals
- Product-wise averages
- Product-wise maximum values
- Product-wise minimum values
- Product-wise standard deviations


In [4]:
#Product-wise totals
Product_wise_totals = np.sum(sales,axis=0)
print("Product-wise totals : ",Product_wise_totals)
#Product-wise averages
Product_wise_averages = np.mean(sales,axis=0)
print("Product-wise Averages : ",Product_wise_averages)
#Product-wise maximum values
Product_wise_max = np.max(sales,axis=0)
print("Product-wise max : ",Product_wise_max)
#Product-wise minimum values
Product_wise_min = np.min(sales,axis=0)
print("Product-wise minimum : ",Product_wise_min)
#Product-wise standard deviations
Product_wise_std = np.std(sales,axis=0)
print("Product-wise std : ",Product_wise_std)

Product-wise totals :  [151 221 197 276 243]
Product-wise Averages :  [30.2 44.2 39.4 55.2 48.6]
Product-wise max :  [35 48 42 60 52]
Product-wise minimum :  [25 40 36 50 45]
Product-wise std :  [3.54400903 2.85657137 2.15406592 3.54400903 2.41660919]


## Task 3 – Week-Wise Analysis

Calculate:

- Weekly totals
- Weekly averages
- Best-performing week
- Lowest-performing week

In [5]:
#Weekly totals
Weekly_totals = np.sum(sales,axis=1)
print("Weekly totals : ",Weekly_totals)
#Weekly averages
Weekly_averages = np.mean(sales,axis=1)
print("Weekly Averages : ",Weekly_averages)
#Best-performing week
print("Best-performing week : ",np.argmax(Weekly_totals))
#Lowest-performing week
print("Lowest-performing week : ",np.argmin(Weekly_totals))

Weekly totals :  [198 210 215 237 228]
Weekly Averages :  [39.6 42.  43.  47.4 45.6]
Best-performing week :  3
Lowest-performing week :  0


## Task 4 – Highest-Selling Product

Identify:

- The product with the highest total sales
- The product with the lowest total sales


In [6]:
#The product with the highest total sales
print("product with the highest total sales : ",np.argmax(Product_wise_totals))
#The product with the lowest total sales
print("product with the lowest total sales : ",np.argmin(Product_wise_totals))

product with the highest total sales :  3
product with the lowest total sales :  0


## Task 5 – Boolean Masking

Find:

- All sales values greater than 50
- All values below 40
- All values between 40 and 55 inclusive

In [7]:
#All sales values greater than 50
print("sales values greater than 50 : ",sales[sales>50])
#All values below 40
print("All values below 40 : ",sales[sales<40])
#All values between 40 and 55 inclusive
print("All values between 40 and 55 inclusive : ",sales[(sales>=40)&(sales<=55)])

sales values greater than 50 :  [55 53 60 52 58]
All values below 40 :  [25 38 30 36 28 35 33]
All values between 40 and 55 inclusive :  [40 50 45 42 55 47 45 40 53 49 48 42 52 46 41 50]


## Task 6 – Logical Row Analysis

Identify weeks where:

- Every product sold more than 35
- At least one product sold more than 55
- Every product sold at least 40

In [20]:
#Every product sold more than 35
print("Every product sold more than 35 : ",np.where(np.all((sales>35),axis=1))[0])
#At least one product sold more than 55
print("At least one product sold more than 55 : ",np.where(np.any((sales>55),axis=1))[0])
#Every product sold at least 40
print("Every product sold at least 40 : ",np.where(np.all((sales>=40),axis=1))[0])

Every product sold more than 35 :  []
At least one product sold more than 55 :  [3 4]
Every product sold at least 40 :  []


## Task 7 – Broadcasting

Without modifying the original dataset:

- Increase Product 2 sales by 10%
- Increase all products by 5%
- Reduce Product 4 sales by 8%

In [24]:
#Increase Product 2 sales by 10%
sales_copy = sales.copy().astype(float)
sales_copy[:,1] *= 1.10
print("Increase Product 2 sales by 10% : \n",sales_copy)
#Increase all products by 5%
sales_copy *= 1.05
print("Increase all products by 5% : \n",sales_copy)
#Reduce Product 4 sales by 8%
sales_copy[:,3] *= 0.92
print("Reduce Product 4 sales by 8% : \n",sales_copy)

Increase Product 2 sales by 10% : 
 [[25.  44.  38.  50.  45. ]
 [30.  46.2 36.  55.  47. ]
 [28.  49.5 40.  53.  49. ]
 [35.  52.8 42.  60.  52. ]
 [33.  50.6 41.  58.  50. ]]
Increase all products by 5% : 
 [[26.25  46.2   39.9   52.5   47.25 ]
 [31.5   48.51  37.8   57.75  49.35 ]
 [29.4   51.975 42.    55.65  51.45 ]
 [36.75  55.44  44.1   63.    54.6  ]
 [34.65  53.13  43.05  60.9   52.5  ]]
Reduce Product 4 sales by 8% : 
 [[26.25  46.2   39.9   48.3   47.25 ]
 [31.5   48.51  37.8   53.13  49.35 ]
 [29.4   51.975 42.    51.198 51.45 ]
 [36.75  55.44  44.1   57.96  54.6  ]
 [34.65  53.13  43.05  56.028 52.5  ]]


## Task 8 – Product Ranking

Rank products from highest to lowest based on total sales.

In [26]:
print("Product ranking based on totals : \n",np.argsort(Product_wise_totals)[::-1])

Product ranking based on totals : 
 [3 4 1 2 0]


## Task 9 – Summary Table

Create a NumPy summary table containing:

- Product Total
- Product Average
- Product Maximum
- Product Minimum
- Product Standard Deviation

Each row should represent one product.

In [27]:
p_total = np.transpose(Product_wise_totals)
p_average = np.transpose(Product_wise_averages)
p_max = np.transpose(Product_wise_max)
p_min = np.transpose(Product_wise_min)
p_std = np.transpose(Product_wise_std)

table = np.column_stack((p_total,p_average,p_max,p_min,p_std))

print("table : \n",table)

table : 
 [[151.          30.2         35.          25.           3.54400903]
 [221.          44.2         48.          40.           2.85657137]
 [197.          39.4         42.          36.           2.15406592]
 [276.          55.2         60.          50.           3.54400903]
 [243.          48.6         52.          45.           2.41660919]]


## 📈 Business Insights

### Insight 1

Product 4 consistently recorded the highest sales among all products, indicating strong customer demand and stable performance. Maintaining sufficient inventory and continuing successful promotional strategies for this product could help sustain overall revenue growth.

---

### Insight 2

The weekly sales trend showed gradual improvement over time, suggesting that overall business performance remained stable and slightly increased during the observed period. Understanding the factors that contributed to stronger-performing weeks could help replicate similar results in future sales cycles.

# 📊 Assessment Reflection

## Tasks Completed Without Help

- Completed all technical NumPy tasks independently, including dataset exploration, statistical analysis, Boolean masking, broadcasting, product ranking, and summary table creation.
- Successfully applied multiple NumPy concepts together without referring to previous notebooks.
- Solved 9 out of 10 tasks confidently.

---

## Tasks That Required Extra Thinking

- Creating the NumPy summary table required additional thought, particularly choosing the correct stacking function to organize multiple statistical arrays into a structured table.
- Writing business insights was less technical and required shifting from numerical analysis to interpreting the results from a business perspective.

---

## Concepts I Remembered Clearly

- Array creation and properties
- Indexing and slicing
- Fancy indexing
- Boolean masking
- Broadcasting
- Aggregation functions
- Axis operations
- Searching and sorting
- Statistical analysis
- Summary statistics

---

## Concepts That Need More Revision

- Translating numerical analysis into business recommendations.
- Building more confidence in presenting analytical findings through written insights.
- Continue practicing complex NumPy problems that combine multiple concepts.

---

## Most Useful NumPy Concept

Broadcasting was the most useful concept because it allowed me to perform large-scale transformations and simulate real-world business scenarios efficiently without using loops. It significantly simplified operations such as applying promotional increases and discounts across selected products.

---

## Self-Assessment Score

**Score:** **9 / 10**

### Why not 10?

While I was able to solve all the technical tasks independently, I found the business insight section less engaging and realized that interpreting analytical results into business recommendations is a skill I need to continue developing.

---

## Confidence Rating

⭐⭐⭐⭐☆

# ⚡ NumPy Quick Revision Guide

## Array Creation

- `np.array()` creates a NumPy array.
- `np.arange()` creates values using a start, stop, and step.
- `np.linspace()` creates evenly spaced values.
- `np.zeros()` and `np.ones()` create initialized arrays.

---

## Important Array Attributes

- `.shape` → dimensions of the array
- `.size` → total number of values
- `.ndim` → number of dimensions
- `.dtype` → data type
- `.nbytes` → total memory used

---

## Indexing and Slicing

- `arr[row, column]` accesses a specific 2D element.
- `arr[:, column]` selects a complete column.
- `arr[row, :]` selects a complete row.
- Slicing usually returns a view.
- Fancy indexing usually returns a copy.

---

## Reshaping

- `reshape()` changes dimensions without changing values.
- `flatten()` creates a 1D copy.
- `.T` transposes rows and columns.

---

## Aggregation and Axis

- `axis=0` performs operations column-wise.
- `axis=1` performs operations row-wise.

Common functions:

- `np.sum()`
- `np.mean()`
- `np.median()`
- `np.min()`
- `np.max()`
- `np.std()`
- `np.var()`

---

## Boolean Masking

Boolean masking filters data using conditions.

Important rules:

- Use `&` instead of `and`
- Use `|` instead of `or`
- Use `~` for NOT
- Wrap each condition in parentheses

---

## Broadcasting

Broadcasting allows operations between arrays with compatible shapes.

It is useful for:

- Applying product-specific increases
- Simulating promotions
- Adjusting columns
- Performing transformations without loops

---

## Searching and Ranking

- `np.where()` returns matching indices.
- `np.argmax()` returns the index of the maximum value.
- `np.argmin()` returns the index of the minimum value.
- `np.argsort()` returns sorting indices.
- `np.unique()` finds unique values and frequencies.

---

## Stacking

- `np.vstack()` adds rows.
- `np.hstack()` joins arrays horizontally.
- `np.column_stack()` converts 1D arrays into columns.

---

## Copy vs View

- A view shares memory with the original.
- A copy owns separate memory.
- Changes to a view may affect the original.
- Use `.copy()` when preserving the original data is important.