## Day 1 Backlog - Basic Operations

In [30]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

In [31]:
'''Perform:
a + b;
b - a;
a * b;
b / a;
a ** 2;
'''

'Perform:\na + b;\nb - a;\na * b;\nb / a;\na ** 2;\n'

In [32]:
print(a+b)


[ 7  9 11 13 15]


In [33]:
print(b-a)

[5 5 5 5 5]


In [34]:
print(a*b)

[ 6 14 24 36 50]


In [35]:
print(b/a)

[6.         3.5        2.66666667 2.25       2.        ]


In [36]:
print(a**2)

[ 1  4  9 16 25]


Mini Check

In [37]:
#Create an array with numbers 1–20.
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [38]:
#Extract only the even numbers.
print(a[a%2==0])

[ 2  4  6  8 10 12 14 16 18 20]


In [39]:
#Reshape it into 4 × 5.
print(np.reshape(a,(4,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [40]:
'''
Print:
shape
size
ndim
dtype 
'''
print(np.shape(a))
print(np.size(a))
print(np.ndim(a))

(20,)
20
1
