# Day 4 – Advanced NumPy Operations

**Date:** July 9, 2026

**Theme:** Advanced NumPy

**Study Time:** ~5–6 Hours

---

## 🎯 Objectives

Today's learning goals:

- Understand the difference between **Copy** and **View**
- Learn how to **sort** NumPy arrays
- Find **unique values** and their frequencies
- Search arrays efficiently
- Stack and split arrays
- Apply these concepts to realistic datasets

---

# 📖 1. Copy vs View

## Theory

Read about:

- View
- Copy
- Memory sharing
- `.base`
- `.copy()`

---

## Dataset

**Array A**

```
[10, 20, 30, 40, 50]
```

---

## 🎯 Tasks

Without using loops:

- Create a **view** of Array A.
- Create a **copy** of Array A.
- Modify the first element of the view.
- Observe the original array.
- Modify the second element of the copy.
- Observe the original array.
- Check whether the arrays share memory.

---

In [1]:
import numpy as np
A = np.array([10, 20, 30, 40, 50])
print(A)

[10 20 30 40 50]


In [2]:
#Create a **view** of Array A.
B=A
print(B)

[10 20 30 40 50]


In [3]:
#Create a **copy** of Array A.
C=A.copy()
print(C)

[10 20 30 40 50]


In [4]:
#Modify the first element of the view.
#Observe the original array.
B[0]=100
print(A)

[100  20  30  40  50]


In [5]:
#Modify the second element of the copy.
#Observe the original array.
C[1]=100
print("Original array : ",A)
print("Copy :",C)

Original array :  [100  20  30  40  50]
Copy : [ 10 100  30  40  50]


# 📖 2. Sorting Arrays

## Theory

Read about:

- `sort()`
- `argsort()`

---

## Dataset

```
[45, 12, 87, 23, 56, 91, 34, 67, 18, 72]
```

---

## 🎯 Tasks

Without using loops:

- Sort the array in ascending order.
- Sort the array in descending order.
- Find the indices that would sort the array.
- Find the three largest values.
- Find the three smallest values.

---

In [6]:
dataset =  np.array([45, 12, 87, 23, 56, 91, 34, 67, 18, 72])
print("Unsorted Dataset : ", dataset)

Unsorted Dataset :  [45 12 87 23 56 91 34 67 18 72]


In [7]:
#sort in ascending
sorted_dataset = np.sort(dataset)
print("Ascendingly Sorted Dataset : ", sorted_dataset)

Ascendingly Sorted Dataset :  [12 18 23 34 45 56 67 72 87 91]


In [8]:
#sort in descending
desc_sorted_dataset = np.sort(dataset)[::-1]
print(desc_sorted_dataset)

[91 87 72 67 56 45 34 23 18 12]


In [9]:
#Find indices that would sort the array
print(np.argsort(dataset))

[1 8 3 6 0 4 7 9 2 5]


In [10]:
#Find three largest values
print(desc_sorted_dataset[:3])

[91 87 72]


In [11]:
#Find three smallest Values
print(sorted_dataset[:3])

[12 18 23]


# 📖 3. Unique Values

## Theory

Read about:

- `unique()`

---

## Dataset

```
[2, 4, 6, 2, 8, 6, 4, 10, 12, 8, 6, 14, 16, 2, 18]
```

---

## 🎯 Tasks

Without using loops:

- Find all unique values.
- Count the number of unique values.
- Count the frequency of each value.
- Identify the most frequent value.

---

In [12]:
unique_dataset = np.array([2, 4, 6, 2, 8, 6, 4, 10, 12, 8, 6, 14, 16, 2, 18])
print(unique_dataset)

[ 2  4  6  2  8  6  4 10 12  8  6 14 16  2 18]


In [13]:
#Find all unique values
unique_values = (np.unique(unique_dataset))
print(unique_values)

[ 2  4  6  8 10 12 14 16 18]


In [14]:
#Count the number of unique values
print(np.size(unique_values))

9


In [15]:
#Count the frequency of each value
unique_values, counts = (np.unique(unique_dataset, return_counts=True))
print(counts)

[3 2 3 2 1 1 1 1 1]


In [16]:
#Find the most frequent value
index_of_most_frequent_unique_value = np.argmax(counts)
print(unique_values[index_of_most_frequent_unique_value])

2


# 📖 4. Searching Arrays

## Theory

Read about:

- `where()`
- `argmax()`
- `argmin()`

---

## Dataset

```
[12, 45, 67, 23, 89, 45, 90, 34, 12, 78, 65, 89]
```

---

## 🎯 Tasks

Without using loops:

- Find all indices where the value is **45**.
- Find indices of values greater than **70**.
- Find the position of the maximum value.
- Find the position of the minimum value.
- Find the indices of all even numbers.

---

In [17]:
array = np.array([12, 45, 67, 23, 89, 45, 90, 34, 12, 78, 65, 89])
print(array)

[12 45 67 23 89 45 90 34 12 78 65 89]


In [18]:
#Find all indices where the value is 45
print(np.where(array==45))

(array([1, 5]),)


In [19]:
#Find all indices greater than 75
print(np.where(array>70))

(array([ 4,  6,  9, 11]),)


In [20]:
#Find position of max value
print(np.argmax(array))

6


In [21]:
#Find position of min value
print(np.argmin(array))

0


In [22]:
#Find indices of all even numbers
print(np.where(array%2==0))

(array([0, 6, 7, 8, 9]),)


# 📖 5. Stacking Arrays

## Theory

Read about:

- Vertical stacking
- Horizontal stacking
- Column stacking

---

## Dataset

### Array A

```
[[1,2],
 [3,4]]
```

### Array B

```
[[5,6],
 [7,8]]
```

---

## 🎯 Tasks

Without using loops:

- Perform vertical stacking.
- Perform horizontal stacking.
- Perform column stacking.
- Compare the output shapes.
- Explain when each stacking method should be used.

---

In [23]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("A : ",A)
print("B : ",B)

A :  [[1 2]
 [3 4]]
B :  [[5 6]
 [7 8]]


In [24]:
#Perform vertical stacking
print(np.vstack((A,B)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
#Perform horizontal stacking
print(np.hstack((A,B)))

[[1 2 5 6]
 [3 4 7 8]]


In [26]:
#Perform Column stacking
print(np.column_stack((A,B)))

[[1 2 5 6]
 [3 4 7 8]]


# 📖 6. Splitting Arrays

## Theory

Read about:

- `split()`
- `hsplit()`
- `vsplit()`

---

## Dataset

Numbers from **1 to 24**

---

## 🎯 Tasks

Without using loops:

- Split into 2 equal parts.
- Split into 3 equal parts.
- Split into 4 equal parts.
- Perform horizontal splits.
- Perform vertical splits.

---

In [27]:
arr = np.arange(1,25)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [28]:
#Split into two equal parts
print(np.split(arr,2))

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])]


In [29]:
#Split into 3 equal parts
print(np.split(arr,3))

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15, 16]), array([17, 18, 19, 20, 21, 22, 23, 24])]


In [30]:
#Split into 4 equal parts
print(np.split(arr,4))

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12]), array([13, 14, 15, 16, 17, 18]), array([19, 20, 21, 22, 23, 24])]


In [31]:
#perform horizontal splits
print(np.hsplit(arr,2))

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])]


In [32]:
#perform Vertical splits
print(np.vsplit(arr.reshape((12,2)),2))

[array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]]), array([[13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])]


# ⭐ Mini Challenge – Sales Data Analysis

## Scenario

A retail store recorded product sales for 20 consecutive days.

---

## Dataset

```
[120, 135, 150, 120, 180,
 175, 160, 150, 145, 170,
 200, 195, 180, 175, 160,
 155, 145, 140, 135, 130]
```

---

## 🎯 Tasks

### Analysis

- Find total sales.
- Find average daily sales.
- Find highest sales.
- Find lowest sales.
- Find median sales.
- Find standard deviation.

---

### Searching

- Find all days where sales were **180**.
- Find days where sales were above the average.
- Find days where sales were below **150**.

---

### Unique Values

- Find unique sales values.
- Count the frequency of each value.
- Identify the most frequent sales value.

---

### Sorting

- Display the top 5 highest sales values.
- Display the bottom 5 lowest sales values.

---

In [33]:
sales_data = np.array([120, 135, 150, 120, 180,
 175, 160, 150, 145, 170,
 200, 195, 180, 175, 160,
 155, 145, 140, 135, 130])
print(sales_data)

[120 135 150 120 180 175 160 150 145 170 200 195 180 175 160 155 145 140
 135 130]


### Analysis

In [34]:
#Find total sales.
print("total sales = ", np.sum(sales_data))
#Find average daily sales.
print("Average Daily Sale = ",np.mean(sales_data))
#Find highest sales.
print("Highest Sales = ",np.max(sales_data))
#Find lowest sales.
print("Lowest Sales = ",np.min(sales_data))
#Find median sales.
print("Median Sales = ",np.median(sales_data))
#Find standard deviation.
print("Standard Deviation = ",np.std(sales_data))

total sales =  3120
Average Daily Sale =  156.0
Highest Sales =  200
Lowest Sales =  120
Median Sales =  152.5
Standard Deviation =  22.67156809750927


### Searching

In [35]:
#Find all days where sales were **180**.
days_where_sales_were_180 = np.where(sales_data==180)
print("days where sales were 180 : ",days_where_sales_were_180)
#Find days where sales were above the average.
abv_avg = np.where(sales_data>np.mean(sales_data))
print("days where sales were above the average : ",abv_avg)
#Find days where sales were below **150**.
below_150 = np.where(sales_data<150)
print("days where sales were below 150 : ",below_150)

days where sales were 180 :  (array([ 4, 12]),)
days where sales were above the average :  (array([ 4,  5,  6,  9, 10, 11, 12, 13, 14]),)
days where sales were below 150 :  (array([ 0,  1,  3,  8, 16, 17, 18, 19]),)


### Unique Values

In [36]:
#Find unique sales values.
print("Unique sales Value : ", np.unique(sales_data))
#Count the frequency of each value.
print("Frequecy of each element : ",np.unique_counts(sales_data))

Unique sales Value :  [120 130 135 140 145 150 155 160 170 175 180 195 200]
Frequecy of each element :  UniqueCountsResult(values=array([120, 130, 135, 140, 145, 150, 155, 160, 170, 175, 180, 195, 200]), counts=array([2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1]))


### Sorting

In [37]:
#Display the top 5 highest sales values.
print("top 5 sales values are : ",np.sort(sales_data)[::-1][:5])
#Display the bottom 5 lowest sales values.
print("bottom 5 sales values are : ",np.sort(sales_data)[:5])

top 5 sales values are :  [200 195 180 180 175]
bottom 5 sales values are :  [120 120 130 135 135]


# 🌟 Bonus Challenge – Movie Ratings Analysis

## Scenario

A movie platform collected ratings from 30 users.

---

## Dataset

```
[4.5, 3.8, 4.9, 4.2, 3.5,
 5.0, 4.8, 4.1, 3.9, 4.7,
 4.3, 3.6, 4.4, 4.0, 4.6,
 4.8, 3.7, 4.9, 4.2, 3.8,
 4.1, 5.0, 4.7, 4.3, 3.9,
 4.6, 4.4, 3.5, 4.8, 4.2]
```

---

## 🎯 Tasks

### Statistics

- Find the average rating.
- Find the highest rating.
- Find the lowest rating.
- Find the median rating.
- Find the standard deviation.

---

### Filtering

Find ratings:

- Greater than **4.5**
- Less than **4.0**
- Between **4.0** and **4.8** (inclusive)

---

### Searching

- Find all indices where the rating is **5.0**
- Find all indices where the rating is **4.8**

---

### Unique Values

- Find all unique ratings.
- Count the frequency of each rating.
- Identify the most common rating.

---

### Sorting

- Sort ratings in ascending order.
- Sort ratings in descending order.
- Display the top 5 ratings.

---

### Statistics

In [38]:
movie_ratings = np.array([4.5, 3.8, 4.9, 4.2, 3.5,
 5.0, 4.8, 4.1, 3.9, 4.7,
 4.3, 3.6, 4.4, 4.0, 4.6,
 4.8, 3.7, 4.9, 4.2, 3.8,
 4.1, 5.0, 4.7, 4.3, 3.9,
 4.6, 4.4, 3.5, 4.8, 4.2])
print(movie_ratings)

[4.5 3.8 4.9 4.2 3.5 5.  4.8 4.1 3.9 4.7 4.3 3.6 4.4 4.  4.6 4.8 3.7 4.9
 4.2 3.8 4.1 5.  4.7 4.3 3.9 4.6 4.4 3.5 4.8 4.2]


In [39]:
#Find the average rating.
print("Average Rating : ",np.mean(movie_ratings))
#Find the highest rating.
print("Highest Rating : ",np.max(movie_ratings))
#Find the lowest rating.
print("Lowest Rating : ",np.min(movie_ratings))
#Find the median rating.
print("Median Rating : ",np.median(movie_ratings))
#Find the standard deviation.
print("Standard Deviation : ",np.std(movie_ratings))

Average Rating :  4.306666666666667
Highest Rating :  5.0
Lowest Rating :  3.5
Median Rating :  4.3
Standard Deviation :  0.45308816900123194


### Filtering

In [40]:
#Greater than **4.5**
print("Greater than 4.5 : ", movie_ratings[movie_ratings>4.5])
#Less than **4.0**
print("Less than 4.0 : ",movie_ratings[movie_ratings<4.0])
#Between **4.0** and **4.8** (inclusive)
print("Between 4.0 and 4.8 (inclusive) : ", movie_ratings[(movie_ratings>=4.0)&(movie_ratings<=4.8)])

Greater than 4.5 :  [4.9 5.  4.8 4.7 4.6 4.8 4.9 5.  4.7 4.6 4.8]
Less than 4.0 :  [3.8 3.5 3.9 3.6 3.7 3.8 3.9 3.5]
Between 4.0 and 4.8 (inclusive) :  [4.5 4.2 4.8 4.1 4.7 4.3 4.4 4.  4.6 4.8 4.2 4.1 4.7 4.3 4.6 4.4 4.8 4.2]


### Searching

In [41]:
#Find all indices where the rating is 5.0
print("all indices where the rating is 5.0 : ", np.where(movie_ratings==5.0))
#Find all indices where the rating is 4.8
print("all indices where the rating is 4.8 : ", np.where(movie_ratings==4.8))

all indices where the rating is 5.0 :  (array([ 5, 21]),)
all indices where the rating is 4.8 :  (array([ 6, 15, 28]),)


### Unique Values

In [42]:
#Find all unique ratings.
print("all unique ratings : ", np.unique(movie_ratings))
#Count the frequency of each rating.
unique_ratings, counts = np.unique_counts(movie_ratings)
print("frequency of each rating. : ", counts)
#Identify the most common rating.
print("the most common rating : ", unique_ratings[np.argmax(counts)])

all unique ratings :  [3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5. ]
frequency of each rating. :  [2 1 1 2 2 1 2 3 2 2 1 2 2 3 2 2]
the most common rating :  4.2


### Sorting

In [43]:
#Sort ratings in ascending order.
print("ratings in ascending order : ", np.sort(movie_ratings))
#Sort ratings in descending order.
print("ratings in descending order : ",np.sort(movie_ratings)[::-1])
#Display the top 5 ratings.
print("top 5 ratings : ", np.sort(movie_ratings)[::-1][:5])

ratings in ascending order :  [3.5 3.5 3.6 3.7 3.8 3.8 3.9 3.9 4.  4.1 4.1 4.2 4.2 4.2 4.3 4.3 4.4 4.4
 4.5 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.9 4.9 5.  5. ]
ratings in descending order :  [5.  5.  4.9 4.9 4.8 4.8 4.8 4.7 4.7 4.6 4.6 4.5 4.4 4.4 4.3 4.3 4.2 4.2
 4.2 4.1 4.1 4.  3.9 3.9 3.8 3.8 3.7 3.6 3.5 3.5]
top 5 ratings :  [5.  5.  4.9 4.9 4.8]
