# 🚀 Project Atlas

# Day 5 – NumPy Mastery & Problem Solving

**Date:** July 10, 2026

**Theme:** Thinking in NumPy

**Study Time:** ~4–5 Hours

---

# 🎯 Objectives

Today's goal is to strengthen problem-solving using NumPy by combining multiple concepts instead of learning isolated functions.

By the end of today, I should be able to:

- Apply Fancy Indexing
- Solve advanced Boolean Masking problems
- Manipulate arrays efficiently
- Combine multiple NumPy operations
- Analyze realistic datasets

---

# 📖 1. Fancy Indexing


## Dataset

Matrix A

```
[[11,12,13,14],
 [21,22,23,24],
 [31,32,33,34],
 [41,42,43,44]]
```

---

## 🎯 Tasks

Without using loops:

- Extract rows 1 and 3.
- Extract columns 2 and 4.
- Extract the elements:
  - 11
  - 23
  - 34
  - 42
- Extract the four corner elements.
- Reverse the row order using indexing.

---

In [9]:
import numpy as np

arr = np.array([[11,12,13,14],
 [21,22,23,24],
 [31,32,33,34],
 [41,42,43,44]])
print(arr)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [10]:
#Extract rows 1 and 3.
print(arr[:3:2,:])
#Extract columns 2 and 4.
print(arr[:,1:4:2])
#Extract the elements: - 11 - 23 - 34 - 42
print("print 11 : ",arr[0,0])
print("print 23 : ",arr[1,2])
print("print 34 : ",arr[2,3])
print("print 42 : ",arr[3,1])

#Extract the four corner elements.
print("Corner Elements : ",arr[::3,::3])
#Reverse the row order using indexing.
print("Reverse the row : ",arr[::-1,:])

[[11 12 13 14]
 [31 32 33 34]]
[[12 14]
 [22 24]
 [32 34]
 [42 44]]
print 11 :  11
print 23 :  23
print 34 :  34
print 42 :  42
Corner Elements :  [[11 14]
 [41 44]]
Reverse the row :  [[41 42 43 44]
 [31 32 33 34]
 [21 22 23 24]
 [11 12 13 14]]


# 📖 2. Advanced Boolean Masking

## Dataset

Daily Temperatures (°C)

```
[32,35,38,29,27,
40,41,36,33,30,
28,31,39,42,37,
34,26,25,43,44]
```

---

## 🎯 Tasks

Without using loops:

- Find temperatures above 35°C.
- Find temperatures below 30°C.
- Find temperatures between 30°C and 38°C.
- Find indices where temperatures exceed 40°C.
- Count readings above 35°C.

---

In [11]:
temperatures = np.array([32,35,38,29,27,
40,41,36,33,30,
28,31,39,42,37,
34,26,25,43,44])
print(temperatures)

[32 35 38 29 27 40 41 36 33 30 28 31 39 42 37 34 26 25 43 44]


In [12]:
#Find temperatures above 35°C.
print("temperatures above 35°C : ",temperatures[temperatures>35])
#Find temperatures below 30°C.
print("temperatures below 30°C : ",temperatures[temperatures<30])
#Find temperatures between 30°C and 38°C.
print("temperatures between 30°C and 38°C : ",temperatures[(temperatures>30) & (temperatures<38)])
#Find indices where temperatures exceed 40°C.
print("indices where temperatures exceed 40°C : ",np.where(temperatures>40))
#Count readings above 35°C.
print("Count readings above 35°C : ",np.size(temperatures[temperatures>35]))

temperatures above 35°C :  [38 40 41 36 39 42 37 43 44]
temperatures below 30°C :  [29 27 28 26 25]
temperatures between 30°C and 38°C :  [32 35 36 33 31 37 34]
indices where temperatures exceed 40°C :  (array([ 6, 13, 18, 19]),)
Count readings above 35°C :  9


# 📖 3. Advanced Array Manipulation

## Dataset

Numbers from **1 to 36**

---

## 🎯 Tasks

Without using loops:

- Reshape into a 6×6 matrix.
- Extract the center 2×2 block.
- Extract only the border elements.
- Replace all even numbers with 0 (without modifying the original).
- Replace all values greater than 25 with -1.

---

In [13]:
numbers = np.arange(1,37)
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [14]:
numbers = numbers.reshape((6,6))
#Reshape into a 6×6 matrix.
print("Reshape into a 6×6 matrix : ",numbers)
#Extract the center 2×2 block.
print("center 2×2 block : ",numbers[2:4,2:4])
#Extract only the border elements.
print("only the border elements : ",numbers[:6:5,:6:5])
#Replace all even numbers with 0 (without modifying the original).
copy = numbers.copy()
copy[copy%2==0]=0
print("all even numbers with 0 (without modifying the original) : ",copy)
#Replace all values greater than 25 with -1.
numbers[numbers>25]=-1
print("Replace all values greater than 25 with -1 : ",numbers)

Reshape into a 6×6 matrix :  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
center 2×2 block :  [[15 16]
 [21 22]]
only the border elements :  [[ 1  6]
 [31 36]]
all even numbers with 0 (without modifying the original) :  [[ 1  0  3  0  5  0]
 [ 7  0  9  0 11  0]
 [13  0 15  0 17  0]
 [19  0 21  0 23  0]
 [25  0 27  0 29  0]
 [31  0 33  0 35  0]]
Replace all values greater than 25 with -1 :  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]]


# ⭐ Mini Challenge – Retail Sales Analysis

## Scenario

A retail store recorded weekly sales (₹ in thousands) for five products over six weeks.

---

## Dataset

```
[
 [45,52,38,60,49],
 [48,55,40,63,51],
 [50,58,42,61,54],
 [47,54,39,65,53],
 [52,60,44,67,56],
 [49,57,41,64,55]
]
```

---

## 🎯 Tasks

### Dataset Exploration

- Find the shape.
- Number of weeks.
- Number of products.
- Total data points.

---

### Sales Analysis

- Total sales.
- Weekly sales totals.
- Product-wise sales totals.
- Average weekly sales.
- Average product sales.

---

### Performance

- Highest sale.
- Lowest sale.
- Best-performing week.
- Best-performing product.
- Week with the lowest sales.

---

### Boolean Masking

- Sales greater than 60.
- Products averaging above 50.
- Weeks with total sales above the overall weekly average.

---

### Broadcasting

Without modifying the original dataset:

- Add a ₹5 promotional boost to all sales.
- Increase Product 3 sales by 10%.
- Apply a 5% reduction to simulate returns.

---

In [15]:
sales = np.array([
 [45,52,38,60,49],
 [48,55,40,63,51],
 [50,58,42,61,54],
 [47,54,39,65,53],
 [52,60,44,67,56],
 [49,57,41,64,55]
])
print(sales)

[[45 52 38 60 49]
 [48 55 40 63 51]
 [50 58 42 61 54]
 [47 54 39 65 53]
 [52 60 44 67 56]
 [49 57 41 64 55]]


### Dataset Exploration

In [16]:
#Find the shape.
print("shape : ",np.shape(sales))
#Number of weeks.
x,y = np.shape(sales)
print("Number of weeks : ",x)
#Number of products.
print("Number of products : ",y)
#Total data points.
print("Total data points : ",np.size(sales))b

SyntaxError: invalid syntax (281199733.py, line 9)

### Sales Analysis

In [ ]:
#Total sales.
print("Total sales : ",np.sum(sales))
#Weekly sales totals.
print("Weekly sales totals : ",np.sum(sales,axis=1))
#Product-wise sales totals.
print("Product-wise sales totals : ",np.sum(sales,axis=0))
#Average weekly sales.
print("Weekly sales Average : ",np.mean(sales,axis=1))
#Average product sales.
print("Product sales Average : ",np.mean(sales,axis=0))

Total sales :  1569
Weekly sales totals :  [244 257 265 258 279 266]
Product-wise sales totals :  [291 336 244 380 318]
Weekly sales Average :  [48.8 51.4 53.  51.6 55.8 53.2]
Product sales Average :  [48.5        56.         40.66666667 63.33333333 53.        ]


### Performance

In [ ]:
#Highest sale.
print("Highest sale : ",np.max(sales))
#Lowest sale.
print("Lowest sale : ",np.min(sales))
#Best-performing week.
print("Best-performing week : ",np.argmax(np.sum(sales,axis=1)))
#Best-performing product.
print("Best-performing product : ",np.argmax(np.sum(sales,axis=0)))
#Week with the lowest sales.
print("Week with the lowest sales : ",np.argmin(np.sum(sales,axis=1)))

Highest sale :  67
Lowest sale :  38
Best-performing week :  4
Best-performing product :  3
Week with the lowest sales :  0


### Boolean Masking

In [ ]:
#Sales greater than 60.
print("Sales greater than 60 : ",sales[sales>60])
#Products averaging above 50.
products_average = np.mean(sales,axis=0)
print("Products averaging above 50 : ",np.where(products_average>50))
#Weeks with total sales above the overall weekly average.
weekly_sales_total = np.sum(sales,axis=1)
overall_weekly_average = np.mean(np.sum(sales,axis=1))
print("overall_weekly_average : ",overall_weekly_average)
print("Weeks with total sales above the overall weekly average : ",np.where(weekly_sales_total>overall_weekly_average))


Sales greater than 60 :  [63 61 65 67 64]
Products averaging above 50 :  (array([1, 3, 4]),)
overall_weekly_average :  261.5
Weeks with total sales above the overall weekly average :  (array([2, 4, 5]),)


### Broadcasting

In [ ]:
#Add a ₹5 promotional boost to all sales.
pr = sales.copy().astype(float)
pr+=5
print(pr)
#Increase Product 3 sales by 10%.
pr[:,2] *= 1.10
print("Increase Product 3 sales by 10% : ",pr)
#Apply a 5% reduction to simulate returns.
pr*=0.95
print("5%\ reduction to simulate returns : ",pr)

[[50. 57. 43. 65. 54.]
 [53. 60. 45. 68. 56.]
 [55. 63. 47. 66. 59.]
 [52. 59. 44. 70. 58.]
 [57. 65. 49. 72. 61.]
 [54. 62. 46. 69. 60.]]
Increase Product 3 sales by 10% :  [[50.  57.  47.3 65.  54. ]
 [53.  60.  49.5 68.  56. ]
 [55.  63.  51.7 66.  59. ]
 [52.  59.  48.4 70.  58. ]
 [57.  65.  53.9 72.  61. ]
 [54.  62.  50.6 69.  60. ]]
5%\ reduction to simulate returns :  [[47.5   54.15  44.935 61.75  51.3  ]
 [50.35  57.    47.025 64.6   53.2  ]
 [52.25  59.85  49.115 62.7   56.05 ]
 [49.4   56.05  45.98  66.5   55.1  ]
 [54.15  61.75  51.205 68.4   57.95 ]
 [51.3   58.9   48.07  65.55  57.   ]]


# 🌟 Bonus Challenge – Cricket Tournament Analysis

## Scenario

Runs scored by 25 players during a tournament.

---

## Dataset

```
[78,45,102,66,89,
54,37,120,98,75,
81,64,59,110,43,
92,88,71,56,134,
47,69,83,95,61]
```

---

## 🎯 Tasks

### Statistics

- Mean
- Median
- Standard deviation
- Highest score
- Lowest score

---

### Performance Analysis

- Scores above 100.
- Scores below 50.
- Half-centuries (50–99).
- Centuries (100+).

---

### Ranking

- Top 5 scores.
- Bottom 5 scores.
- Highest scorer.
- Lowest scorer.

---

### Boolean Analysis

- Count scores above the average.
- Count even scores.
- Count odd scores.

---

In [ ]:
runs = np.array([78,45,102,66,89,
54,37,120,98,75,
81,64,59,110,43,
92,88,71,56,134,
47,69,83,95,61])
print(runs)

[ 78  45 102  66  89  54  37 120  98  75  81  64  59 110  43  92  88  71
  56 134  47  69  83  95  61]


### Statistics

In [ ]:
#Mean
print("Mean = ",np.mean(runs))
#Median
print("Median = ",np.median(runs))
#Standard deviation
print("Standard deviation = ",np.std(runs))
#Highest score
print("Highest Score = ",np.max(runs))
#Lowest score
print("Lowest Score = ",np.min(runs))

Mean =  76.68
Median =  75.0
Standard deviation =  24.282866387640485
Highest Score =  134
Lowest Score =  37


### Performance Analysis

In [ ]:
#Scores above 100.
print("Scores above 100 : ",runs[runs>100])
#Scores below 50.
print("Scores below 50 : ",runs[runs<50])
#Half-centuries (50–99).
print("Half-centuries (50–99) : ", np.size(runs[(runs>=50)&(runs<100)]))
#Centuries (100+).
print("Centuries (100+) : ",np.size(runs[runs>=100]))

Scores above 100 :  [102 120 110 134]
Scores below 50 :  [45 37 43 47]
Half-centuries (50–99) :  17
Centuries (100+) :  4


### Ranking

In [ ]:
#Top 5 scores.
print("Top 5 scores : ",np.sort(runs)[::-1][:5])
#Bottom 5 scores.
print("Bottom 5 scores : ",np.sort(runs)[:5])
#Highest scorer.
print("Highest Scorer : ", np.argmax(runs))
#Lowest scorer.
print("Lowest Scorer : ",np.argmin(runs))

Top 5 scores :  [134 120 110 102  98]
Bottom 5 scores :  [37 43 45 47 54]
Highest Scorer :  19
Lowest Scorer :  6


### Boolean Analysis

In [ ]:
#Count scores above the average.
average_runs = np.mean(runs)
print("Count scores above the average : ", np.size(runs[runs>average_runs]))
#Count even scores.
print("Count even scores : ", np.size(runs[runs%2==0]))
#Count odd scores.
print("Count odd scores : ", np.size(runs[runs%2==1]))

Count scores above the average :  12
Count even scores :  12
Count odd scores :  13
