## Day 1 Backlog - Basic Operations

In [30]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

### Perform Operations

1. `a + b`
2. `b - a`
3. `a * b`
4. `b / a`
5. `a ** 2`

In [32]:
print(a+b)


[ 7  9 11 13 15]


In [33]:
print(b-a)

[5 5 5 5 5]


In [34]:
print(a*b)

[ 6 14 24 36 50]


In [35]:
print(b/a)

[6.         3.5        2.66666667 2.25       2.        ]


In [36]:
print(a**2)

[ 1  4  9 16 25]


Mini Check

In [37]:
#Create an array with numbers 1–20.
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [38]:
#Extract only the even numbers.
print(a[a%2==0])

[ 2  4  6  8 10 12 14 16 18 20]


In [39]:
#Reshape it into 4 × 5.
print(np.reshape(a,(4,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
'''
Print:
shape
size
ndim
dtype 
'''
print(np.shape(a))
print(np.size(a))
print(np.ndim(a))

(20,)
20
1


## 🎯 NumPy Indexing & Slicing

In [59]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Practice

- First column
- Last column
- Middle element
- Top-left 2×2 block
- Bottom-right 2×2 block
- Rows 2–4
- Columns 2–4

In [44]:
#First column
print(arr[:,0])

[ 1  6 11 16 21]


In [45]:
#Last column
print(arr[:,-1])

[ 5 10 15 20 25]


In [50]:
#Middle element
i,j=np.shape(arr)
print(arr[i//2 +1][j//2 +1])


19


In [52]:
#Top-left 2×2 block
print(arr[:2,:2])

[[1 2]
 [6 7]]


In [55]:
#Bottom-right 2×2 block
print(arr[-2:,-2:])

[[19 20]
 [24 25]]


In [57]:
#Rows 2–4
print(arr[1:4])

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [58]:
#Columns 2–4
print(arr[:,1:4])

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


# Day 2: NumPy Basics

## Reshaping Arrays

In [60]:
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [67]:
#Reshape
reshaped_arr=arr.reshape(2,10)
print(reshaped_arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [68]:
#flatten
flattened_arr=reshaped_arr.flatten()
print(flattened_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [70]:
#ravel
ravel_arr=reshaped_arr.ravel()
print(ravel_arr)
print(reshaped_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [71]:
#Transpose
transpose=reshaped_arr.transpose()
print(transpose)

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]


## 🎯 Aggregation Functions

In [73]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [74]:
sum_arr=np.sum(arr)
print(sum_arr)

78


In [75]:
mean_of_array=np.mean(arr)
print(mean_of_array)

6.5


In [76]:
max_in_arr=np.max(arr)
print(max_in_arr)

12


In [ ]:
min_in_arr=np.min(arr)
print(min_in_arr)

1


In [78]:
standard_deviation=np.std(arr)
print(standard_deviation)

3.452052529534663


In [79]:
variance=np.var(arr)
print(variance)

11.916666666666666


In [ ]:
print(np.sum(arr, axis=0))
#adds the numbers in same column

[15 18 21 24]


In [83]:
print(np.sum(arr, axis=1))
#adds the numbers in same row

[10 26 42]


In [ ]:
#calculates mean in same column
print(np.mean(arr, axis=0))

[5. 6. 7. 8.]


In [85]:
#calculates mean in same row
print(np.mean(arr, axis=1))

[ 2.5  6.5 10.5]


## 🌟 Bonus XP

### Challenge:

Without using loops:

1. Print the diagonal.
2. Print the last three rows.
3. Print the first three columns.
4. Find the average of each row.
5. Find the maximum value in each column.

In [87]:
arr = np.arange(1, 101).reshape(10, 10)
print(arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [88]:
#Print the diagonal
print(np.diagonal(arr))

[  1  12  23  34  45  56  67  78  89 100]


In [ ]:
#print the last three rows
print(arr[-3:,:])

[[ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [90]:
#print first three columns
print(arr[:,:3])

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]
 [51 52 53]
 [61 62 63]
 [71 72 73]
 [81 82 83]
 [91 92 93]]


In [91]:
#Find the average of each row
print(np.mean(arr,axis=1))

[ 5.5 15.5 25.5 35.5 45.5 55.5 65.5 75.5 85.5 95.5]


In [92]:
#Find the max in each column
print(np.max(arr,axis=0))

[ 91  92  93  94  95  96  97  98  99 100]
