# Day 3 - Broadcasting & Boolean Masking

## Objectives

- Broadcasting
- Vectorization
- Boolean Masking
- Random Numbers
- Mini Project

In [1]:
import numpy as np

## 1. Broadcasting

In [2]:
a = np.array([1,2,3])

print(a + 5)

[6 7 8]


In [3]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix + 10)

[[11 12 13]
 [14 15 16]]


In [4]:
row = np.array([1,2,3])

print(matrix + row)

[[2 4 6]
 [5 7 9]]


In [5]:
col = np.array([[1],
                [2]])

print(matrix + col)

[[2 3 4]
 [6 7 8]]


In [6]:
print(matrix + np.array([1,2]))
#because both rows and columns should be equal or either of both should have 1

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
print(matrix + np.array([1,2,3]))
#This works because matrix is (2,3) and new array is (1,3); both have 3 columns and one of them has 1 row. It is valid even if the conditions are reversed

[[2 4 6]
 [5 7 9]]


## 2. Vectorized Operations

In [ ]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(arr * 5)

[ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
print(arr + 100)

[101 102 103 104 105 106 107 108 109 110]


In [ ]:
print(arr ** 3)

[   1    8   27   64  125  216  343  512  729 1000]


In [ ]:
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [ ]:
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [ ]:
print(np.exp(arr))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


### Key Takeaway

NumPy performs element-wise operations without explicit loops, making the code shorter and more efficient.

## 3. Boolean Masking

### What is Boolean Masking?

#### When is it useful?
#### Ans. We can use it for filtering without using loops
#### Why is it important in Data Analysis?
#### Ans. It makes complex operations and filtering easy

### Dataset

Numbers from 1 to 40

In [ ]:
arr= np.arange(1,41)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


### Tasks

Return:

- Even numbers
- Odd numbers
- Numbers greater than 20
- Multiples of 3
- Multiples of both 2 and 5
- Numbers between 12 and 28
- Numbers not divisible by 4

In [ ]:
#Even numbers
mask_even = arr%2==0
print(arr[mask_even])

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [ ]:
#Odd numbers
mask_odd = arr%2==1
print(arr[mask_odd])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [ ]:
#Numbers greater than 20
mask_20 = arr>20
print(arr[mask_20])

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [ ]:
mask_multiples_of_3 = arr%3==0
print(arr[mask_multiples_of_3])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39]


In [ ]:
#Multiples of both 2 and 5
mask_multiples_of_2_and_5 = (arr%2==0) & (arr%5==0)
print(arr[mask_multiples_of_2_and_5])

[10 20 30 40]


In [ ]:
#Numbers between 12 and 28
mask_numbers_12_to_28 = (arr>11) & (arr<29)
print(arr[mask_numbers_12_to_28])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]


In [ ]:
#Numbers not divisible by 4
mask_not_by_4 = ~(arr%4==0)
print(arr[mask_not_by_4])

[ 1  2  3  5  6  7  9 10 11 13 14 15 17 18 19 21 22 23 25 26 27 29 30 31
 33 34 35 37 38 39]


## 4. Random Number Generation

### Tasks

Generate:

- 10 random decimal numbers
- 4×4 random matrix
- 20 random integers
- Two identical arrays using the same seed

In [ ]:
#10 random decimal numbers
r=np.random.uniform(1,10,10)
print(r)

[3.28033629 8.58449739 5.89234613 3.28400402 4.04440437 8.25715175
 8.49804106 3.26015691 9.55682926 2.50314669]


In [ ]:
#4×4 random matrix
r=np.random.uniform(1,10,(4,4))
print(r)

[[4.59006497 8.8165     4.27215502 1.51628957]
 [4.11320704 2.74631017 3.32433153 9.59641162]
 [9.61943645 4.21359966 1.03336317 5.24560096]
 [8.96215175 2.04024335 3.51530503 9.43861325]]


In [ ]:
#20 random integers
r=np.random.default_rng()
print(r.integers(1,101,20))

[ 62  71  38   2  89 100  48  38  65  50  95  16  34  92   3  39  98  41
  78  48]


In [ ]:
#Two identical arrays using the same seed
# 1. Initialize the generator with a specific seed (e.g., 42)
rng1 = np.random.default_rng(seed=5)
array1 = rng1.integers(low=1, high=100, size=5)

# 2. Re-initialize a new generator with the EXACT same seed
rng2 = np.random.default_rng(seed=5)
array2 = rng2.integers(low=1, high=100, size=5)

print("Array 1:", array1)
print("Array 2:", array2)


Array 1: [67 80  3 80 47]
Array 2: [67 80  3 80 47]


# ⭐ Mini Challenge – Student Marks Analysis

## Scenario

You are given the marks of **8 students** in **3 subjects**.

- Each row represents a student.
- Each column represents a subject.

---

## Dataset

| Student | Subject 1 | Subject 2 | Subject 3 |
|---------|----------:|----------:|----------:|
| Student 1 | 78 | 82 | 91 |
| Student 2 | 65 | 70 | 68 |
| Student 3 | 90 | 88 | 95 |
| Student 4 | 55 | 60 | 58 |
| Student 5 | 84 | 79 | 81 |
| Student 6 | 73 | 69 | 77 |
| Student 7 | 92 | 94 | 90 |
| Student 8 | 48 | 52 | 57 |

Create this dataset as a NumPy array before solving the tasks.

---

# 🎯 Tasks

Without using loops:

### Basic Analysis

- Find the shape of the dataset.
- Find the number of students.
- Find the number of subjects.

---

### Statistics

- Find the overall average marks.
- Find the average marks of each student.
- Find the average marks of each subject.
- Find the highest mark.
- Find the lowest mark.

---

### Student Performance

- Find the total marks scored by each student.
- Identify the student with the highest total marks.
- Identify the student with the lowest total marks.

---

### Boolean Masking

Find:

- Students whose average marks are above 80.
- Students whose average marks are below 60.
- Students who scored above 90 in any subject.
- Students who scored above 75 in all subjects.

---

### Broadcasting

Without modifying the original dataset:

- Add 5 grace marks to every student.
- Add 2 bonus marks only to Subject 2.

---

In [ ]:
student_marks= np.array([
 [78,82,91],
 [65,70,68],
 [90,88,95],
 [55,60,58],
 [84,79,81],
 [73,69,77],
 [92,94,90],
 [48,52,57]
])
print(student_marks)

[[78 82 91]
 [65 70 68]
 [90 88 95]
 [55 60 58]
 [84 79 81]
 [73 69 77]
 [92 94 90]
 [48 52 57]]


### Basic Analysis

In [ ]:
#shape of dataset
print(np.shape(student_marks))

(8, 3)


In [ ]:
#number of students and subjects
students, subjects = np.shape(student_marks)
print("Number of students : ",students)
print("Number of subjects : ",subjects)

Number of students :  8
Number of subjects :  3


### Statistics

In [ ]:
# Find the overall average marks.
overall_mean = np.mean(student_marks)
print(overall_mean)

74.83333333333333


In [ ]:
# Find the average marks of each student.
student_average_marks = np.mean(student_marks,axis=1)
print(student_average_marks)

[83.66666667 67.66666667 91.         57.66666667 81.33333333 73.
 92.         52.33333333]


In [ ]:
# Find the average marks of each subject.
subject_average_marks = np.mean(student_marks,axis=0)
print(subject_average_marks)

[73.125 74.25  77.125]


In [ ]:
# Find the highest mark.
highest_mark = np.max(student_marks)
print(highest_mark)

95


In [ ]:
# Find the lowest mark.
lowest_mark = np.min(student_marks)
print(lowest_mark)

48


### Student Performance

In [ ]:
#Find the total marks scored by each student.
total_each_stu = np.sum(student_marks,axis=1)
print(total_each_stu)

[251 203 273 173 244 219 276 157]


In [ ]:
#Identify the student with the highest total marks.
stu_with_highest = np.argmax(total_each_stu)
print(stu_with_highest)

6


In [ ]:
#Identify the student with the lowest total marks.
stu_with_lowest = np.argmin(total_each_stu)
print(stu_with_lowest)

7


### Boolean Masking

In [ ]:
#Students whose average marks are below 60.
mask_1 = student_average_marks<60
print(np.where(mask_1)[0])

[3 7]


In [ ]:
#Students who scored above 90 in any subject.
mask_2 = np.max(student_marks,axis=1) > 90
print(np.where(mask_2)[0])

[0 2 6]


In [ ]:
#Students whose average marks are above 80.
mask_3 = student_average_marks>80
print(np.where(mask_3)[0])

[0 2 4 6]


In [ ]:
#Students who scored above 75 in all subjects.
mask_4 = (student_marks>75).all(axis=1)
print(np.where(mask_4)[0])

[0 2 4 6]


### Broadcasting

In [ ]:
#Add 5 grace marks to every student.
print(student_marks+5)

[[ 83  87  96]
 [ 70  75  73]
 [ 95  93 100]
 [ 60  65  63]
 [ 89  84  86]
 [ 78  74  82]
 [ 97  99  95]
 [ 53  57  62]]


In [ ]:
#Add 2 bonus marks only to Subject 2.
student_marks[:, 1]+=2
print(student_marks)

[[78 84 91]
 [65 72 68]
 [90 90 95]
 [55 62 58]
 [84 81 81]
 [73 71 77]
 [92 96 90]
 [48 54 57]]


# 🌟 Bonus Challenge – Employee Salary Analysis

## Scenario

You are given the monthly salaries (in ₹) of **30 employees**.

Treat this as a one-dimensional NumPy array.

---

## Dataset

```text
[28000, 35000, 42000, 50000, 38000,
 45000, 52000, 61000, 47000, 39000,
 56000, 49000, 65000, 70000, 33000,
 41000, 53000, 62000, 58000, 46000,
 37000, 72000, 68000, 54000, 43000,
 59000, 76000, 48000, 51000, 64000]
```

Create this dataset as a NumPy array before solving the tasks.

---

# 🎯 Tasks

Without using loops:

## Dataset Exploration

- Find the total number of employees.
- Find the highest salary.
- Find the lowest salary.
- Find the average salary.
- Find the median salary.
- Find the standard deviation.
- Find the variance.

---

## Salary Analysis

Find:

- Employees earning above ₹60,000.
- Employees earning below ₹40,000.
- Employees earning between ₹45,000 and ₹60,000 (inclusive).
- Employees earning exactly ₹50,000 (if any).

---

## Boolean Masking

Extract:

- Salaries greater than the average salary.
- Salaries less than the average salary.
- Salaries divisible by ₹1,000.
- Salaries divisible by ₹2,000.
- Salaries between ₹50,000 and ₹70,000.

---

## Vectorized Operations

Without modifying the original dataset:

- Give every employee a ₹2,500 bonus.
- Increase every salary by 8%.
- Deduct ₹1,000 from every salary.
- Calculate annual salary for every employee.
- Calculate monthly tax assuming a flat 10% deduction.

---

## Ranking

Find:

- Top 5 highest salaries.
- Bottom 5 lowest salaries.
- Difference between the highest and lowest salary.

---

In [ ]:
salaries = np.array([28000, 35000, 42000, 50000, 38000,
 45000, 52000, 61000, 47000, 39000,
 56000, 49000, 65000, 70000, 33000,
 41000, 53000, 62000, 58000, 46000,
 37000, 72000, 68000, 54000, 43000,
 59000, 76000, 48000, 51000, 64000])
print(salaries)

[28000 35000 42000 50000 38000 45000 52000 61000 47000 39000 56000 49000
 65000 70000 33000 41000 53000 62000 58000 46000 37000 72000 68000 54000
 43000 59000 76000 48000 51000 64000]


## Dataset Exploration

In [ ]:
#Find the total number of employees.
print(np.size(salaries))

30


In [ ]:
#Find the highest salary.
print(np.max(salaries))

76000


In [ ]:
#Find the lowest salary.
print(np.min(salaries))

28000


In [ ]:
#Find the average salary.
print(np.mean(salaries))

51400.0


In [ ]:
#Find the median salary.
print(np.median(salaries))

50500.0


In [ ]:
#Find the standard deviation.
print(np.std(salaries))

12115.004471040584


In [ ]:
#Find the variance.
print(np.var(salaries))

146773333.33333334


## Salary Analysis

In [ ]:
#Employees earning above ₹60,000.
mask_60k = salaries>60000
print(np.where(mask_60k)[0])

[ 7 12 13 17 21 22 26 29]


In [ ]:
#Employees earning below ₹40,000.
mask_below_40k = salaries<40000
print(np.where(mask_below_40k)[0])

[ 0  1  4  9 14 20]


In [ ]:
#Employees earning between ₹45,000 and ₹60,000 (inclusive).
mask_bw_45k_to_60k = (salaries>=45000) & (salaries<60000)
print(np.where(mask_bw_45k_to_60k)[0])

[ 3  5  6  8 10 11 16 18 19 23 25 27 28]


In [ ]:
#Employees earning exactly ₹50,000 (if any).
mask_50k = salaries==50000
print(np.where(mask_50k)[0])

[3]


## Boolean Masking

In [ ]:
#Salaries greater than the average salary.
mask_greater_avg = salaries>(np.average(salaries))
print(salaries[mask_greater_avg])

[52000 61000 56000 65000 70000 53000 62000 58000 72000 68000 54000 59000
 76000 64000]


In [ ]:
#Salaries less than the average salary.
mask_lessthan_avg = salaries<(np.average(salaries))
print(salaries[mask_lessthan_avg])

[28000 35000 42000 50000 38000 45000 47000 39000 49000 33000 41000 46000
 37000 43000 48000 51000]


In [ ]:
#Salaries divisible by ₹1,000.
mask_1000 = salaries%1000==0
print(salaries[mask_1000])

[53000.]


In [ ]:
#Salaries divisible by ₹2,000.
mask_2000 = salaries%2000==0
print(salaries[mask_2000])

[]


In [ ]:
#Salaries between ₹50,000 and ₹70,000.
mask_sal_bw_50k_70k = (salaries>50000) & (salaries<70000)
print(salaries[mask_sal_bw_50k_70k])

[53000. 55160. 64880. 59480. 51920. 69200. 56240. 65960. 61640. 57320.
 62720. 50840. 54080. 68120.]


## Vectorized Operations

In [ ]:
#Give every employee a ₹2,500 bonus.
print(salaries+2500)

[31740. 39300. 46860. 55500. 42540. 50100. 57660. 67380. 52260. 43620.
 61980. 54420. 71700. 77100. 37140. 45780. 58740. 68460. 64140. 51180.
 41460. 79260. 74940. 59820. 47940. 65220. 83580. 53340. 56580. 70620.]


In [ ]:
#Increase every salary by 8%.
salaries = salaries*1.08
print(salaries)

[31579.2 39744.  47908.8 57240.  43243.2 51408.  59572.8 70070.4 53740.8
 44409.6 64238.4 56073.6 74736.  80568.  37411.2 46742.4 60739.2 71236.8
 66571.2 52574.4 42076.8 82900.8 78235.2 61905.6 49075.2 67737.6 87566.4
 54907.2 58406.4 73569.6]


In [ ]:
#Deduct ₹1,000 from every salary.
salaries-=1000
print(salaries)

[30579.2 38744.  46908.8 56240.  42243.2 50408.  58572.8 69070.4 52740.8
 43409.6 63238.4 55073.6 73736.  79568.  36411.2 45742.4 59739.2 70236.8
 65571.2 51574.4 41076.8 81900.8 77235.2 60905.6 48075.2 66737.6 86566.4
 53907.2 57406.4 72569.6]


In [ ]:
#Calculate annual salary for every employee.
annual_sal = salaries*12
print(annual_sal)

[ 366950.4  464928.   562905.6  674880.   506918.4  604896.   702873.6
  828844.8  632889.6  520915.2  758860.8  660883.2  884832.   954816.
  436934.4  548908.8  716870.4  842841.6  786854.4  618892.8  492921.6
  982809.6  926822.4  730867.2  576902.4  800851.2 1038796.8  646886.4
  688876.8  870835.2]


In [ ]:
#Calculate monthly tax assuming a flat 10% deduction.
tax= salaries*0.1
print(tax)

[3057.92 3874.4  4690.88 5624.   4224.32 5040.8  5857.28 6907.04 5274.08
 4340.96 6323.84 5507.36 7373.6  7956.8  3641.12 4574.24 5973.92 7023.68
 6557.12 5157.44 4107.68 8190.08 7723.52 6090.56 4807.52 6673.76 8656.64
 5390.72 5740.64 7256.96]


## Ranking

In [ ]:
#Top 5 highest salaries.
print(np.sort(salaries)[-5:][::-1])

[86566.4 81900.8 79568.  77235.2 73736. ]


In [ ]:
#Bottom 5 lowest salaries.
print(np.sort(salaries)[:5])

[30579.2 36411.2 38744.  41076.8 42243.2]


In [ ]:
#Difference between the highest and lowest salary.
print(np.max(salaries)-np.min(salaries))

55987.200000000004
