In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [9]:
a = np.array([[1,2,3],[4,5,6]])

In [10]:
a.shape
a.size
a.ndim
a.dtype

dtype('int64')

In [11]:
a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])

In [ ]:
#First element
print(a[0][0])
#Last element
print(a[-1][-1])
#First row
print(a[0])
#Second row
print(a[1])

10
90
[10 20 30]
[40 50 60]
